/*

 DINOSAUR_MAP1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 18
   Tile set      : dinosaur_map_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define dinosaur_map1Width 32
#define dinosaur_map1Height 18
#define dinosaur_map1Bank 0

extern unsigned char dinosaur_map1[];

/* End of DINOSAUR_MAP1.H */
