/*

 DINOSAUR_SPRITES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 15

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/
#include <gb/gb.h>
#include <gb/metasprites.h>

/* Bank of tiles. */
#define dinosaur_tilesBank 0
/* Start of tile array. */
extern unsigned char dinosaur_tiles[];

const metasprite_t dinosaur_idle[] = {
    {.dy=-8, .dx=-8, .dtile=0, .props=0},
    {.dy=0, .dx=8, .dtile=1, .props=0},
    {.dy=8, .dx=-8, .dtile=2, .props=0},
    {.dy=0, .dx=8, .dtile=3, .props=0},
	METASPR_TERM
};

const metasprite_t dinosaur_lleg[] = {
    {.dy=-8, .dx=-8, .dtile=4, .props=0},
    {.dy=0, .dx=8, .dtile=5, .props=0},
    {.dy=8, .dx=-8, .dtile=6, .props=0},
    {.dy=0, .dx=8, .dtile=7, .props=0},
	METASPR_TERM
};

const metasprite_t dinosaur_rleg[] = {
    {.dy=-8, .dx=-8, .dtile=8, .props=0},
    {.dy=0, .dx=8, .dtile=9, .props=0},
    {.dy=8, .dx=-8, .dtile=10, .props=0},
    {.dy=0, .dx=8, .dtile=11, .props=0},
	METASPR_TERM
};

/* End of DINOSAUR_SPRITES.H */
